version: "3.7"

networks:
  cassandra:

services:
  cassandra-1:
    image: cassandra:3.11.3
    hostname: "cassandra-1"
    healthcheck: &healthcheck
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60
    environment: &environment
      CASSANDRA_SEEDS: "cassandra-1,cassandra-2"    # The first two nodes will be seeds
      CASSANDRA_CLUSTER_NAME: Local
      CASSANDRA_DC: dc1
      CASSANDRA_ENDPOINT_SNITCH: SimpleSnitch
      CASSANDRA_NUM_TOKENS: 256
    volumes:
      - ./cassandra/cassandra-1/data:/var/lib/cassandra
      - ./cassandra/cassandra-1/logs:/var/log/cassandra
    networks:
      - cassandra
    ports:
      - "9042:9042"

  cassandra-2:
    image: cassandra:3.11.3
    hostname: "cassandra-2"
    healthcheck: *healthcheck
    networks:
      - cassandra
    environment: *environment
    volumes:
      - ./cassandra/cassandra-2/data:/var/lib/cassandra
      - ./cassandra/cassandra-2/logs:/var/log/cassandra

  cassandra-3:
    image: cassandra:3.11.3
    hostname: "cassandra-3"
    healthcheck: *healthcheck
    networks:
      - cassandra
    environment: *environment
    volumes:
      - ./cassandra/cassandra-3/data:/var/lib/cassandra
      - ./cassandra/cassandra-3/logs:/var/log/cassandra
    depends_on:
      cassandra-1:
        condition: service_healthy
